### ISSUE TITLE
Query the route before declaring pod ready

### ISSUE THREAD

**Issue by vrutkovs** [vrutkovs/promecieus#18]
Seems #17 has caused a regression - "Pod is ready" being returned almost instantly now, while the pod is still loading

cc @tjungblu

**Comment by tjungblu** [comment]
let me quickly debug

**Comment by tjungblu** [comment]
for me it's spin-waiting:

![image](https://user-images.githubusercontent.com/85170409/224366548-c7a6bc94-99a1-46db-aa1d-128cbae9ed21.png)

do you have a prow url maybe?

**Comment by tjungblu** [comment]
hmm, I see, I can repro this on the live env. Locally against hypershift from cluster-bot seems to work fine.. odd

**Comment by vrutkovs** [comment]
okay, I'll have a closer look at prod

**Comment by tjungblu** [comment]
seems to me that `waitForDeploymentReady` is simply returning very quickly. Any interesting log message on the promecieus pod?

**Comment by vrutkovs** [comment]
Deployment says the replicaset has progressed:
`
v1.DeploymentStatus{ObservedGeneration:1, Replicas:1, UpdatedReplicas:1, ReadyReplicas:1, AvailableReplicas:1, UnavailableReplicas:0, Conditions:[]v1.DeploymentCondition{v1.DeploymentCondition{Type:"Available", Status:"True", LastUpdateTime:time.Date(2023, time.March, 10, 13, 23, 4, 0, time.Local), LastTransitionTime:time.Date(2023, time.March, 10, 13, 23, 4, 0, time.Local), Reason:"MinimumReplicasAvailable", Message:"Deployment has minimum availability."}, v1.DeploymentCondition{Type:"Progressing", Status:"True", LastUpdateTime:time.Date(2023, time.March, 10, 13, 23, 4, 0, time.Local), LastTransitionTime:time.Date(2023, time.March, 10, 13, 22, 59, 0, time.Local), Reason:"NewReplicaSetAvailable", Message:"ReplicaSet \"uxckiyuz-prom-b94fcdc6c\" has successfully progressed."}}, CollisionCount:(*int32)(nil)}
`

Perhaps we should wait for route to be admitted too

**Comment by tjungblu** [comment]
interesting, then I assume it falls into the `ReadyReplicas:1` case and just returns ready. 

> Perhaps we should wait for route to be admitted too

yeah, I was also thinking of just curling the endpoint. It will return a brief 404 until the WAL is replayed as well.

**Comment by vrutkovs** [comment]
Good idea. Its probably not a regression then :)
